import { Product } from '../types';

export const productsToSync: Omit<Product, 'id' | 'uid' | 'createdAt'>[] = [
  { title: 'Anime Crop Top Y2K Slim #1', category: 'Crop top / top', brand: 'Y2K Streetwear', size: 'S', purchasePrice: 24.21, isSold: false, purchaseDate: new Date('2025-07-04') },
  { title: 'Anime Crop Top Y2K Slim #2', category: 'Crop top / top', brand: 'Y2K Streetwear', size: 'S', purchasePrice: 24.21, isSold: false, purchaseDate: new Date('2025-07-04') },
  { title: 'Anime Crop Top Y2K Slim #3', category: 'Crop top / top', brand: 'Y2K Streetwear', size: 'S', purchasePrice: 24.21, isSold: false, purchaseDate: new Date('2025-07-04') },
  { title: 'Wide Leg Leopard Pants Grey #1', category: 'Spodnie damskie', brand: 'Y2K Casual', size: 'M', purchasePrice: 52.27, isSold: false, purchaseDate: new Date('2025-06-25') },
  { title: 'Wide Leg Leopard Pants Grey #2', category: 'Spodnie damskie', brand: 'Y2K Casual', size: 'M', purchasePrice: 52.27, isSold: false, purchaseDate: new Date('2025-06-25') },
  { title: 'Wide Leg Leopard Pants Grey #3', category: 'Spodnie damskie', brand: 'Y2K Casual', size: 'M', purchasePrice: 52.27, isSold: false, purchaseDate: new Date('2025-06-25') },
  { title: 'Y2K Graphic Tee Harajuku Retro', category: 'Koszulka', brand: 'Y2K Harajuku', size: 'S', purchasePrice: 22.20, isSold: false, purchaseDate: new Date('2025-06-10') },
  { title: 'Vintage Heavy Jeans Y2K #1', category: 'Jeans', brand: 'Y2K Hip Hop', size: 'L', purchasePrice: 182.99, isSold: false, purchaseDate: new Date('2025-06-10') },
  { title: 'Gothpunk Oversized Jeans', category: 'Jeans', brand: 'Harajuku Gothpunk', size: 'L', purchasePrice: 89.59, isSold: false, purchaseDate: new Date('2025-06-10') },
  { title: 'Y2K Baggy Flare Jeans Patchwork', category: 'Jeans', brand: 'Harajuku 2000s', size: 'XXXL', purchasePrice: 117.40, isSold: false, purchaseDate: new Date('2025-11-14') },
  { title: 'Vintage Heavy Jeans Y2K #2', category: 'Jeans', brand: 'Y2K Hip Hop', size: 'L', purchasePrice: 173.36, isSold: false, purchaseDate: new Date('2025-09-20') },
  { title: 'Irregular Denim Patchwork Y2K', category: 'Jeans', brand: 'American Retro Y2K', size: 'L', purchasePrice: 76.83, isSold: false, purchaseDate: new Date('2025-07-25') },
  { title: 'Wide Leg Leopard Pants Grey #4', category: 'Spodnie damskie', brand: 'Y2K Casual', size: 'M', purchasePrice: 67.74, isSold: false, purchaseDate: new Date('2025-07-14') },
  { title: 'Wide Leg Leopard Pants Grey #5', category: 'Spodnie damskie', brand: 'Y2K Casual', size: 'M', purchasePrice: 67.74, isSold: false, purchaseDate: new Date('2025-07-14') },
  { title: 'Aphex Twin Graphic T-shirt White #1', category: 'Koszulka damska', brand: 'Y2K Streetwear', size: 'L', purchasePrice: 17.20, isSold: false, purchaseDate: new Date('2025-07-04') },
  { title: 'Aphex Twin Graphic T-shirt White #2', category: 'Koszulka damska', brand: 'Y2K Streetwear', size: 'L', purchasePrice: 17.20, isSold: false, purchaseDate: new Date('2025-07-04') },
  { title: 'Letter Embroidered Loose Jeans #1', category: 'Jeans', brand: 'American Street Y2K', size: 'L', purchasePrice: 91.99, isSold: false, purchaseDate: new Date('2025-06-10') },
  { title: 'Letter Embroidery Denim Shorts', category: 'Szorty denim', brand: 'American Fashion', size: 'L', purchasePrice: 98.79, isSold: false, purchaseDate: new Date('2025-06-10') },
  { title: 'Gothic Skull Chain T-shirt', category: 'Koszulka', brand: 'Retro Gothic', size: 'L', purchasePrice: 60.64, isSold: false, purchaseDate: new Date('2025-06-10') },
  { title: 'Playboy Carti Death Wish T-shirt', category: 'Koszulka', brand: 'Hip Hop Retro', size: 'L', purchasePrice: 39.19, isSold: false, purchaseDate: new Date('2025-05-31') },
  { title: 'Logo Printed T-shirt Black', category: 'Koszulka', brand: 'Harajuku', size: 'S', purchasePrice: 33.09, isSold: false, purchaseDate: new Date('2025-05-31') },
  { title: 'Summer Y2K Personalized Top', category: 'Top damski', brand: 'American Y2K', size: 'L', purchasePrice: 41.59, isSold: false, purchaseDate: new Date('2025-05-31') },
  { title: 'Affliction Y2K Oversized T-shirt', category: 'Koszulka', brand: 'Y2K Hip Hop', size: 'L', purchasePrice: 29.64, isSold: false, purchaseDate: new Date('2025-05-31') },
  { title: 'Aphex Twin Graphic T-shirt White #3', category: 'Koszulka damska', brand: 'Y2K Streetwear', size: 'L', purchasePrice: 18.99, isSold: false, purchaseDate: new Date('2025-05-31') },
  { title: 'Black Graphic Tee Y2K', category: 'Koszulka', brand: 'Y2K Streetwear', size: '—', purchasePrice: 41.69, isSold: false, purchaseDate: new Date('2025-05-24') },
  { title: 'White Graphic Tee 2024 Y2K', category: 'Koszulka', brand: 'Y2K Streetwear', size: '—', purchasePrice: 41.69, isSold: false, purchaseDate: new Date('2025-05-24') },
  { title: 'Graffiti Hooded Sweatshirt', category: 'Bluza z kapturem', brand: 'Casual Graffiti', size: 'L', purchasePrice: 87.39, isSold: false, purchaseDate: new Date('2025-05-24') },
  { title: 'Vintage Heavy Jeans Y2K #3', category: 'Jeans', brand: 'Y2K Hip Hop', size: 'L', purchasePrice: 182.99, isSold: false, purchaseDate: new Date('2025-05-24') },
  { title: 'Letter Embroidered Loose Jeans #2', category: 'Jeans', brand: 'American Street Y2K', size: 'L', purchasePrice: 86.38, isSold: false, purchaseDate: new Date('2025-05-24') },
  { title: 'Nowe Wysokiej Jakości Amerykańskie Vintage Spodnie Cargo w Moro z Szerokimi nogawkami', category: 'Spodnie Cargo', brand: 'Amerykańskie Vintage', size: 'L', purchasePrice: 73.26, isSold: false, purchaseDate: new Date('2026-03-10') },
  { title: 'Streetwear Y2K Bawełniana Koszulka Harajuku Plaski Nadruk Oversize Punk Krótki Rękaw', category: 'Koszulka / T-shirt', brand: 'Streetwear Y2K Harajuku', size: 'L', purchasePrice: 32.79, isSold: false, purchaseDate: new Date('2026-01-14') },
  { title: 'Streetwear Y2K Bawełniana Koszulka Harajuku Plaski Nadruk Oversize Punk Krótki Rękaw', category: 'Koszulka / T-shirt', brand: 'Streetwear Y2K Harajuku', size: 'L', purchasePrice: 32.79, isSold: false, purchaseDate: new Date('2026-01-14') },
  { title: 'Męskie luźne spodnie dżinsowe z amerykańskim street stylem i nadrukami liter', category: 'Spodnie dżinsowe', brand: 'Brak marki (street style)', size: 'L', purchasePrice: 78.75, isSold: false, purchaseDate: new Date('2026-01-14') },
  { title: 'Sweter Damski na Halloween i Boże Narodzenie - Czarno-Biały Pulower z Grafiką Twarzy', category: 'Sweter', brand: 'Brak marki', size: 'M', purchasePrice: 46.79, isSold: false, purchaseDate: new Date('2026-01-14') },
  { title: 'Misa Vintage Koszulki z Grafiką, T-shirt, Merch, Odzież Anime', category: 'Koszulka / T-shirt', brand: 'Misa Vintage', size: 'S', purchasePrice: 22.88, isSold: false, purchaseDate: new Date('2026-01-14') },
];
